version: 1
source: local_editor
synced_at: '2026-07-27T22:56:23.489616+00:00'
labware:
- id: lw-3918306f45b8
  name: 1536 Labcyte LP-0400 LDV
  kind: sbs_plate
  vendor: ''
  catalog_number: ''
  description: ''
  base_class: microplate
  wells: 1536
  length_mm: 127.76
  width_mm: 85.48
  height_mm: 10.48
  stack_height_mm: 9.8
  gripper_offset_mm: 1.0
  lid_gripper_offset_mm: null
  empty_check_offset_mm: null
  shim_thickness_mm: 0.0
  can_be_sealed: true
  sealed_height_mm: 10.5
  sealed_stacking_height_mm: 9.3
  can_have_lid: false
  lidded_height_mm: 0.0
  lidded_stack_height_mm: 0.0
  lid_resting_height_mm: 0.0
  lid_departure_height_mm: 0.0
  max_robot_handling_speed: fast
  rows: 0
  cols: 0
  well_depth_mm: 5.2
  offset_x_mm: 3.375
  offset_y_mm: 3.375
  spacing_x_mm: 2.25
  spacing_y_mm: 2.25
  well_volume_ul: 5.5
  well_diameter_mm: 1.7
  disposable_tip_capacity_ul: 10.0
  tip_definition_id: ''
  supported_tip_ids: []
  model_3d: /labware-assets/lw-3918306f45b8/1536_Labcyte_LP-0400_LDV.gltf
  can_mount: false
  can_be_mounted: false
- id: lw-34358f93e2a0
  name: 384 CellVis 1.5H
  kind: sbs_plate
  vendor: ''
  catalog_number: ''
  description: ''
  base_class: microplate
  wells: 384
  length_mm: 127.76
  width_mm: 85.48
  height_mm: 14.3
  stack_height_mm: 14.3
  gripper_offset_mm: 8.0
  lid_gripper_offset_mm: 0.5
  empty_check_offset_mm: null
  shim_thickness_mm: 0.0
  can_be_sealed: false
  sealed_height_mm: 0.0
  sealed_stacking_height_mm: 0.0
  can_have_lid: true
  lidded_height_mm: 16.4
  lidded_stack_height_mm: 17.7
  lid_resting_height_mm: 9.7
  lid_departure_height_mm: 11.0
  max_robot_handling_speed: fast
  rows: 0
  cols: 0
  well_depth_mm: 0.0
  offset_x_mm: 0.0
  offset_y_mm: 0.0
  spacing_x_mm: 0.0
  spacing_y_mm: 0.0
  well_volume_ul: 0.0
  well_diameter_mm: 0.0
  disposable_tip_capacity_ul: 0.0
  tip_definition_id: ''
  supported_tip_ids: []
  model_3d: null
  can_mount: false
  can_be_mounted: false
- id: 01KD4PYY7N4EG0E22P3QP1RHB9
  name: 384 Labcyte PP0200 PP sq flt
  kind: sbs_plate
  vendor: Beckman
  catalog_number: 001-14622
  description: Echo(R) Qualified 384-Well Polypropylene Microplate, Clear, Sterile,
    Surface-treated with Amine Coating
  base_class: microplate
  wells: 384
  length_mm: 127.76
  width_mm: 85.48
  height_mm: 14.4
  stack_height_mm: 13.6
  gripper_offset_mm: 7.0
  lid_gripper_offset_mm: null
  empty_check_offset_mm: null
  shim_thickness_mm: 4.0
  can_be_sealed: true
  sealed_height_mm: 0.0
  sealed_stacking_height_mm: 0.0
  can_have_lid: true
  lidded_height_mm: 16.5
  lidded_stack_height_mm: 14.5
  lid_resting_height_mm: 9.5
  lid_departure_height_mm: 8.5
  max_robot_handling_speed: fast
  rows: 16
  cols: 24
  well_depth_mm: 11.4
  offset_x_mm: 2.25
  offset_y_mm: 2.25
  spacing_x_mm: 4.5
  spacing_y_mm: 4.5
  well_volume_ul: 130.0
  well_diameter_mm: 3.5
  disposable_tip_capacity_ul: 10.0
  tip_definition_id: ''
  supported_tip_ids: []
  model_3d: /labware-assets/01KD4PYY7N4EG0E22P3QP1RHB9/384_Greiner_781091_PS_uclear.gltf
  can_mount: false
  can_be_mounted: false
- id: lw-4914769d0af7
  name: 384 V11 ST10 Tip Box 10734.102
  kind: sbs_plate
  vendor: ''
  catalog_number: ''
  description: ''
  base_class: tip_box
  wells: 384
  length_mm: 127.76
  width_mm: 85.48
  height_mm: 50.0
  stack_height_mm: 0.0
  gripper_offset_mm: 10.0
  lid_gripper_offset_mm: null
  empty_check_offset_mm: null
  shim_thickness_mm: 0.0
  can_be_sealed: false
  sealed_height_mm: 0.0
  sealed_stacking_height_mm: 0.0
  can_have_lid: false
  lidded_height_mm: 0.0
  lidded_stack_height_mm: 0.0
  lid_resting_height_mm: 0.0
  lid_departure_height_mm: 0.0
  max_robot_handling_speed: fast
  rows: 0
  cols: 0
  well_depth_mm: 0.0
  offset_x_mm: 2.25
  offset_y_mm: 2.25
  spacing_x_mm: 4.5
  spacing_y_mm: 4.5
  well_volume_ul: 0.0
  well_diameter_mm: 0.0
  disposable_tip_capacity_ul: 10.0
  tip_definition_id: ''
  supported_tip_ids: []
  model_3d: /labware-assets/lw-4914769d0af7/ST_Tip_Box.gltf
  can_mount: false
  can_be_mounted: false
- id: 01KD4P500RXXP69X03R0SDGS7C
  name: 96 Costar 3596 clear cell culture PS flt btm
  kind: sbs_plate
  vendor: Costar
  catalog_number: 3596/3599
  description: "Costar 96-well cell culture plate, clear plate with clear flat bottom\
    \ with lid, polystyrene\n \n Total vol: 360uL\n Working volume: 200uL"
  base_class: microplate
  wells: 96
  length_mm: 127.76
  width_mm: 85.48
  height_mm: 14.3
  stack_height_mm: 13.0
  gripper_offset_mm: 0.0
  lid_gripper_offset_mm: null
  empty_check_offset_mm: null
  shim_thickness_mm: 4.0
  can_be_sealed: false
  sealed_height_mm: 0.0
  sealed_stacking_height_mm: 0.0
  can_have_lid: true
  lidded_height_mm: 16.5
  lidded_stack_height_mm: 16.0
  lid_resting_height_mm: 7.0
  lid_departure_height_mm: 10.0
  max_robot_handling_speed: fast
  rows: 8
  cols: 12
  well_depth_mm: 10.75
  offset_x_mm: 0.0
  offset_y_mm: 0.0
  spacing_x_mm: 9.0
  spacing_y_mm: 9.0
  well_volume_ul: 0.0
  well_diameter_mm: 6.4
  disposable_tip_capacity_ul: 0.0
  tip_definition_id: ''
  supported_tip_ids: []
  model_3d: /models/labware/uploads/01KD4P500RXXP69X03R0SDGS7C/model.gltf
  can_mount: false
  can_be_mounted: false
- id: lw-0188881d2601
  name: 96 Deepwell U-Bottom
  kind: sbs_plate
  vendor: ''
  catalog_number: ''
  description: ''
  base_class: microplate
  wells: 96
  length_mm: 127.76
  width_mm: 85.48
  height_mm: 32.4
  stack_height_mm: 0.0
  gripper_offset_mm: 5.0
  lid_gripper_offset_mm: null
  empty_check_offset_mm: null
  shim_thickness_mm: 0.0
  can_be_sealed: false
  sealed_height_mm: 0.0
  sealed_stacking_height_mm: 0.0
  can_have_lid: false
  lidded_height_mm: 0.0
  lidded_stack_height_mm: 0.0
  lid_resting_height_mm: 0.0
  lid_departure_height_mm: 0.0
  max_robot_handling_speed: fast
  rows: 0
  cols: 0
  well_depth_mm: 32.4
  offset_x_mm: 0.0
  offset_y_mm: 0.0
  spacing_x_mm: 9.0
  spacing_y_mm: 9.0
  well_volume_ul: 200.0
  well_diameter_mm: 6.5
  disposable_tip_capacity_ul: 10.0
  tip_definition_id: ''
  supported_tip_ids: []
  model_3d: /labware-assets/lw-0188881d2601/Part_Studio_1.gltf
  can_mount: false
  can_be_mounted: false
- id: lw-d4fcc14aaa86
  name: 96 Nunc Flatbottom
  kind: sbs_plate
  vendor: ''
  catalog_number: ''
  description: ''
  base_class: microplate
  wells: 96
  length_mm: 127.76
  width_mm: 85.48
  height_mm: 14.4
  stack_height_mm: 0.0
  gripper_offset_mm: 4.0
  lid_gripper_offset_mm: null
  empty_check_offset_mm: null
  shim_thickness_mm: 0.0
  can_be_sealed: false
  sealed_height_mm: 0.0
  sealed_stacking_height_mm: 0.0
  can_have_lid: true
  lidded_height_mm: 16.4
  lidded_stack_height_mm: 17.7
  lid_resting_height_mm: 7.9
  lid_departure_height_mm: 18.0
  max_robot_handling_speed: fast
  rows: 0
  cols: 0
  well_depth_mm: 9.0
  offset_x_mm: 0.0
  offset_y_mm: 0.0
  spacing_x_mm: 9.0
  spacing_y_mm: 9.0
  well_volume_ul: 100.0
  well_diameter_mm: 6.4
  disposable_tip_capacity_ul: 10.0
  tip_definition_id: ''
  supported_tip_ids: []
  model_3d: null
  can_mount: false
  can_be_mounted: false
- id: lw-b0704e550d2a
  name: 96 V11 LT200 Tip Box 06880.002
  kind: sbs_plate
  vendor: ''
  catalog_number: ''
  description: ''
  base_class: tip_box
  wells: 96
  length_mm: 127.76
  width_mm: 85.48
  height_mm: 49.9
  stack_height_mm: 0.0
  gripper_offset_mm: 10.0
  lid_gripper_offset_mm: null
  empty_check_offset_mm: null
  shim_thickness_mm: 0.0
  can_be_sealed: false
  sealed_height_mm: 0.0
  sealed_stacking_height_mm: 0.0
  can_have_lid: false
  lidded_height_mm: 0.0
  lidded_stack_height_mm: 0.0
  lid_resting_height_mm: 0.0
  lid_departure_height_mm: 0.0
  max_robot_handling_speed: fast
  rows: 0
  cols: 0
  well_depth_mm: 0.0
  offset_x_mm: 0.0
  offset_y_mm: 0.0
  spacing_x_mm: 9.0
  spacing_y_mm: 9.0
  well_volume_ul: 0.0
  well_diameter_mm: 0.0
  disposable_tip_capacity_ul: 10.0
  tip_definition_id: ''
  supported_tip_ids: []
  model_3d: null
  can_mount: false
  can_be_mounted: false
- id: lw-651f80d816b1
  name: TestPlate
  kind: sbs_plate
  vendor: ''
  catalog_number: ''
  description: ''
  base_class: microplate
  wells: 96
  length_mm: 127.76
  width_mm: 85.48
  height_mm: 13.2
  stack_height_mm: 12.1
  gripper_offset_mm: 5.0
  lid_gripper_offset_mm: null
  empty_check_offset_mm: null
  shim_thickness_mm: 0.0
  can_be_sealed: false
  sealed_height_mm: 0.0
  sealed_stacking_height_mm: 0.0
  can_have_lid: false
  lidded_height_mm: 0.0
  lidded_stack_height_mm: 0.0
  lid_resting_height_mm: 0.0
  lid_departure_height_mm: 0.0
  max_robot_handling_speed: fast
  rows: 0
  cols: 0
  well_depth_mm: 0.0
  offset_x_mm: 0.0
  offset_y_mm: 0.0
  spacing_x_mm: 0.0
  spacing_y_mm: 0.0
  well_volume_ul: 0.0
  well_diameter_mm: 0.0
  disposable_tip_capacity_ul: 0.0
  tip_definition_id: ''
  supported_tip_ids: []
  model_3d: null
  can_mount: false
  can_be_mounted: false
